Dec 06 2018 14:10:52 flaskAPIBridge.py main line:33: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Dec 06 2018 14:22:55 flaskAPIBridge.py main line:31: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Dec 06 2018 14:24:54 flaskAPIBridge.py main line:31: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
